const promptsData = [
  {
    "ID": "SLS-OUT-001",
    "Category": "Outreach",
    "Stage": "Prospecting",
    "Use Case": "Personalized cold outreach email",
    "When to Use": "首次接觸陌生客戶、需要快速產出可寄出的冷開發信。",
    "Required Inputs": "job_title, company, product, background, cta, tone, length",
    "Variable List": "{{job_title}}=目標職稱\n{{company}}=公司名稱\n{{product}}=產品/方案\n{{background}}=ICP/痛點/價值主張\n{{cta}}=希望的下一步\n{{tone}}=語氣\n{{length}}=字數",
    "Prompt Quick ZH": "請寫一封冷開發 Email 給 {{company}} 的 {{job_title}}，介紹 {{product}}。背景與客製化依據：{{background}}。語氣：{{tone}}；長度：{{length}}。輸出：3 個主旨 + 可直接寄出的正文，並包含 CTA：{{cta}}。",
    "Prompt Robust ZH": "請扮演資深 B2B 業務，寫一封給 {{company}} 的 {{job_title}} 的冷開發 Email，目標是引起興趣並促成 {{cta}}。\n只使用我提供的資訊：{{background}}。\n規則：1) 不要空泛稱讚；2) 不要捏造客戶現況；3) 主文控制在 {{length}} 內；4) 語氣 {{tone}}；5) 若缺關鍵資訊，先問我最多 3 個問題。\n輸出：A. 主旨 3 個 B. 正文 1 版。",
    "Prompt Reference EN": "Write a short, compelling cold email to a [job title] at [company name] introducing our product. Use the background below to customize it. Background: [insert value props or ICP info]. Format it in email-ready text.",
    "Output Format": "主旨 3 個 + Email 正文 1 版",
    "Notes": "避免使用未驗證的客戶事實。可搭配公司新聞或近期事件提高客製化程度。",
    "Source URL": "https://academy.openai.com/public/clubs/work-users-ynjqu/resources/use-cases-sales"
  },
  {
    "ID": "SLS-OUT-002",
    "Category": "Outreach",
    "Stage": "Demo",
    "Use Case": "Rework demo follow-up email",
    "When to Use": "demo 結束後，要拉下一步（POC、技術評估、採購流程）。",
    "Required Inputs": "original_email, recap_notes, cta",
    "Variable List": "{{original_email}}=原始 email\n{{recap_notes}}=會議重點/需求\n{{cta}}=下一步行動",
    "Prompt Quick ZH": "請把這封 demo 後跟進信改寫成更顧問式的版本：{{original_email}}。請加入需求摘要、demo 重點對應、下一步與 CTA：{{cta}}。補充資訊：{{recap_notes}}。",
    "Prompt Robust ZH": "請改寫以下 demo follow-up email，使其更「顧問式、客戶導向、可促進下一步」。\n原信：{{original_email}}\n補充：{{recap_notes}}\n必含：1) 客戶需求摘要 2) demo 重點如何對應需求 3) 明確下一步與 CTA：{{cta}} 4) 若對方猶豫時的替代方案。\n規則：避免過度推銷；避免冗長；若資訊不足，先問我最多 3 個問題。\n輸出：主旨 3 個 + 正文 1 版。",
    "Prompt Reference EN": "Rewrite this follow-up email after a demo to sound more consultative. Original email: [paste here]. Include recap, next steps, and call scheduling CTA. Output as email text.",
    "Output Format": "主旨 3 個 + Email 正文 1 版",
    "Notes": "這張卡片最適合搭配實際會議摘要一起使用。",
    "Source URL": "https://academy.openai.com/public/clubs/work-users-ynjqu/resources/use-cases-sales"
  },
  {
    "ID": "SLS-OUT-003",
    "Category": "Outreach",
    "Stage": "Renewal",
    "Use Case": "Renewal pitch for key customer",
    "When to Use": "續約前、商務 review、要強化 ROI 與續約理由時。",
    "Required Inputs": "customer, renewal_history, value_data, renewal_recommendation, objections",
    "Variable List": "{{customer}}=客戶\n{{renewal_history}}=歷史方案/價格\n{{value_data}}=使用/成果/ROI\n{{renewal_recommendation}}=建議方案\n{{objections}}=可能異議",
    "Prompt Quick ZH": "請為 {{customer}} 產出一段續約 pitch，根據以下資訊：續約歷史 {{renewal_history}}；價值/ROI {{value_data}}；建議方案 {{renewal_recommendation}}。請給我短 pitch + 可選跟進 email。",
    "Prompt Robust ZH": "請扮演客戶續約顧問，為 {{customer}} 撰寫一份續約短 pitch。\n資料：續約歷史={{renewal_history}}；價值/ROI={{value_data}}；建議方案={{renewal_recommendation}}；可能異議={{objections}}。\n規則：1) 優先用可量化價值；2) 不確定的數字標註待確認；3) 強調續約理由與風險降低。\n輸出：A. 90 秒口頭 pitch B. 3-5 個 ROI proof points C. 可選跟進 email。",
    "Prompt Reference EN": "Draft a renewal pitch for [customer name] based on this renewal history and value data: [paste data]. Include key ROI proof points and renewal recommendation. Output as a short pitch and optional follow-up email.",
    "Output Format": "90秒 pitch + ROI 重點 + 可選 email",
    "Notes": "若有真實 KPI，放在 {{value_data}} 會讓輸出品質大幅提升。",
    "Source URL": "https://academy.openai.com/public/clubs/work-users-ynjqu/resources/use-cases-sales"
  },
  {
    "ID": "SLS-OUT-004",
    "Category": "Outreach",
    "Stage": "Daily Ops",
    "Use Case": "Summary of rep activity",
    "When to Use": "主管每天想快速掌握一線活動。",
    "Required Inputs": "inputs, audience, tone",
    "Variable List": "{{inputs}}=通話摘要/CRM 匯出\n{{audience}}=接收者\n{{tone}}=語氣",
    "Prompt Quick ZH": "請根據以下資料，寫一則 rep 每日活動摘要給 {{audience}}：{{inputs}}。輸出 3–5 點 bullet，語氣 {{tone}}。",
    "Prompt Robust ZH": "請根據 {{inputs}}，寫一則可直接貼到 Slack 或 Email 的「每日 rep 活動摘要」。\n接收者：{{audience}}；語氣：{{tone}}。\n規則：只用我提供的內容，不要推測；每點包含「客戶/機會 + 發生什麼 + 下一步」；控制在 3–5 點。",
    "Prompt Reference EN": "Write a daily update summarizing key rep activities. Inputs: [paste call summaries or CRM exports]. Make it upbeat and concise. Output as 3–5 bullet message.",
    "Output Format": "3–5 點 bullet",
    "Notes": "很適合做成每天固定流程或自動化。",
    "Source URL": "https://academy.openai.com/public/clubs/work-users-ynjqu/resources/use-cases-sales"
  },
  {
    "ID": "SLS-OUT-005",
    "Category": "Outreach",
    "Stage": "Mgmt",
    "Use Case": "Exec update on pipeline status",
    "When to Use": "週會、月會、管會、forecast review。",
    "Required Inputs": "pipeline_data, timeframe",
    "Variable List": "{{pipeline_data}}=pipeline 資料\n{{timeframe}}=時間區間",
    "Prompt Quick ZH": "請用高階主管可快速閱讀的方式，總結 {{timeframe}} pipeline 健康狀況。資料：{{pipeline_data}}。需含總 pipeline、top risks、biggest wins、forecast confidence。",
    "Prompt Robust ZH": "請根據 {{pipeline_data}}，撰寫一段 {{timeframe}} 的 pipeline executive update。\n必含：1) 總 pipeline 與趨勢 2) biggest wins 3) top risks（含原因） 4) forecast confidence（高/中/低與依據）。\n規則：簡潔、可執行、不堆砌數字；若資料不足先列出待補資料。",
    "Prompt Reference EN": "Summarize our pipeline health this month for execs. Inputs: [paste data]. Include total pipeline, top risks, biggest wins, and forecast confidence. Write it like a short exec update.",
    "Output Format": "8-12 行內管理摘要",
    "Notes": "建議搭配固定欄位資料，品質最穩。",
    "Source URL": "https://academy.openai.com/public/clubs/work-users-ynjqu/resources/use-cases-sales"
  },
  {
    "ID": "SLS-PLN-001",
    "Category": "Strategy",
    "Stage": "Account Planning",
    "Use Case": "Strategic account plan",
    "When to Use": "關鍵帳戶、續約前 90 天、QBR 前。",
    "Required Inputs": "customer, company_profile, priorities, current_usage, stakeholders, renewal_date",
    "Variable List": "{{customer}}=客戶\n{{company_profile}}=公司概況\n{{priorities}}=已知優先事項\n{{current_usage}}=現況使用\n{{stakeholders}}=利害關係人\n{{renewal_date}}=日期",
    "Prompt Quick ZH": "請為 {{customer}} 建立 account plan。輸入：{{company_profile}}、{{priorities}}、{{current_usage}}、{{stakeholders}}、{{renewal_date}}。輸出結構：目標、風險、機會、下一步。",
    "Prompt Robust ZH": "請為 {{customer}} 產出一份策略型 Account Plan。\n資料：公司概況={{company_profile}}；優先事項={{priorities}}；現況使用={{current_usage}}；利害關係人={{stakeholders}}；續約日期={{renewal_date}}。\n輸出：1) 90/180天目標 2) 風險與早期徵兆 3) 機會（擴張/交叉銷售） 4) Stakeholder map 5) 30/60/90 行動清單。\n若關鍵資訊不足，先問我最多 5 個問題。",
    "Prompt Reference EN": "Create an account plan for [customer name]. Use these inputs: company profile, known priorities, current product usage, stakeholders, and renewal date. Output a structured plan with goals, risks, opportunities, and next steps.",
    "Output Format": "結構化 account plan",
    "Notes": "可搭配 CS / AE 一起共用。",
    "Source URL": "https://academy.openai.com/public/clubs/work-users-ynjqu/resources/use-cases-sales"
  },
  {
    "ID": "SLS-PLN-002",
    "Category": "Strategy",
    "Stage": "Planning",
    "Use Case": "Territory planning framework",
    "When to Use": "年度規劃、重劃區域、資源配置。",
    "Required Inputs": "headcount, industries, regions, historical_revenue",
    "Variable List": "{{headcount}}=人力\n{{industries}}=產業\n{{regions}}=區域\n{{historical_revenue}}=歷史營收",
    "Prompt Quick ZH": "請為下一財年設計 territory planning 指南。輸入：{{headcount}}、{{industries}}、{{regions}}、{{historical_revenue}}。請推薦分配方法與 sample coverage plan。",
    "Prompt Robust ZH": "請扮演銷售規劃顧問，為下一財年設計 territory planning framework。\n資料：人力={{headcount}}；產業={{industries}}；區域={{regions}}；歷史營收={{historical_revenue}}。\n輸出：1) 至少 2 種 territory 分配方法與優缺點 2) 建議 coverage model 3) sample 分配表 4) 每月追蹤指標與風險。",
    "Prompt Reference EN": "Create a territory planning guide for our next fiscal year. Inputs: team headcount, target industries, regions, and historical revenue. Recommend allocation method and sample coverage plan.",
    "Output Format": "策略指南 + sample plan",
    "Notes": "很適合讓主管快速對齊思路，不直接取代正式規劃模型。",
    "Source URL": "https://academy.openai.com/public/clubs/work-users-ynjqu/resources/use-cases-sales"
  },
  {
    "ID": "SLS-PLN-003",
    "Category": "Strategy",
    "Stage": "Prospecting",
    "Use Case": "Prioritize accounts using firmographic data",
    "When to Use": "要從一長串名單找出最值得先打的帳戶。",
    "Required Inputs": "account_list, criteria",
    "Variable List": "{{account_list}}=名單\n{{criteria}}=排序條件",
    "Prompt Quick ZH": "我有這份 accounts 清單：{{account_list}}。請依 {{criteria}} 排序，輸出 ranked list 並說明原因。",
    "Prompt Robust ZH": "請依據 {{criteria}}（例如產業、規模、募資、tech stack）對 {{account_list}} 進行排序。\n輸出：1) Top 20 ranked list 2) 每家公司 1-2 句原因 3) 每家公司建議的第一封外聯切入點。",
    "Prompt Reference EN": "I have this list of accounts: [paste sample]. Prioritize them based on [criteria: industry, size, funding, tech stack]. Output a ranked list with reasons why.",
    "Output Format": "Top 20 + 原因 + 外聯切入點",
    "Notes": "如果 criteria 先定義好權重，品質會更穩。",
    "Source URL": "https://academy.openai.com/public/clubs/work-users-ynjqu/resources/use-cases-sales"
  },
  {
    "ID": "SLS-PLN-004",
    "Category": "Strategy",
    "Stage": "Prospecting",
    "Use Case": "High-potential accounts using weighted scoring",
    "When to Use": "已有多個指標，想做半結構化評分。",
    "Required Inputs": "scoring_rules, account_data",
    "Variable List": "{{scoring_rules}}=加權規則\n{{account_data}}=帳戶資料",
    "Prompt Quick ZH": "請依 {{scoring_rules}} 為 {{account_data}} 打分，輸出 Top 10 帳戶、總分與原因。",
    "Prompt Robust ZH": "請根據以下規則為 accounts 打分並排序：{{scoring_rules}}。資料：{{account_data}}。\n輸出：1) Top 10（公司、總分、各項分數拆解）2) 每家 1 句值得追的原因 3) Top 3 的外聯切入點與 CTA。",
    "Prompt Reference EN": "Score accounts based on [insert rules—e.g., company size, engagement score, intent signals]. Data: [Upload account list]. Output top 10 ranked accounts with their score and a note explaining why.",
    "Output Format": "Top 10 + 分數拆解",
    "Notes": "建議把 scoring_rules 寫清楚，避免 AI 自行假設權重。",
    "Source URL": "https://academy.openai.com/public/clubs/work-users-ynjqu/resources/use-cases-sales"
  },
  {
    "ID": "SLS-PLN-005",
    "Category": "Strategy",
    "Stage": "Expansion",
    "Use Case": "Regional market entry planning",
    "When to Use": "評估新國家、新區域、新市場的銷售可行性。",
    "Required Inputs": "region, solution, constraints",
    "Variable List": "{{region}}=地區/國家\n{{solution}}=方案\n{{constraints}}=限制/假設",
    "Prompt Quick ZH": "我正在評估進入 {{region}} 推廣 {{solution}}。請研究購買行為、競品、經濟條件與法規風險，輸出 go/no-go 簡報摘要與行動建議。",
    "Prompt Robust ZH": "請針對 {{region}} 的 {{solution}} 市場進入機會做研究。限制/假設：{{constraints}}。\n輸出需包含：1) 在地購買行為 2) 競品/替代方案 3) 經濟與法規風險 4) go/no-go 建議 5) 90 天行動步驟。\n若使用外部資訊，請附來源連結。",
    "Prompt Reference EN": "I’m evaluating market entry into [region/country] for our [SaaS solution]. Research local buying behaviors, competitive landscape, economic conditions, and regulatory concerns. Format as a go/no-go market readiness summary with citations and action steps.",
    "Output Format": "Go/No-go 摘要 + 行動建議",
    "Notes": "適合搭配網路研究或 Deep Research。",
    "Source URL": "https://academy.openai.com/public/clubs/work-users-ynjqu/resources/use-cases-sales"
  },
  {
    "ID": "SLS-COMP-001",
    "Category": "Competitive",
    "Stage": "Enablement",
    "Use Case": "Battlecard for competitor",
    "When to Use": "業務需要快速掌握競品優劣與對話話術。",
    "Required Inputs": "competitor, notes",
    "Variable List": "{{competitor}}=競品\n{{notes}}=定位/既有筆記",
    "Prompt Quick ZH": "請為競品 {{competitor}} 做一張 battlecard。資料：{{notes}}。請包含強項、弱項、我們如何贏、quick talk track，表格輸出。",
    "Prompt Robust ZH": "請根據 {{notes}}，為 {{competitor}} 產出一張可直接給 reps 使用的 battlecard。\n輸出表格欄位：定位一句話、強項、弱項、我們如何贏、30 秒話術、2 分鐘話術、不能說/易踩雷。",
    "Prompt Reference EN": "Create a battlecard for [competitor name]. Use these notes: [insert positioning data]. Include strengths, weaknesses, how we win, and quick talk track. Output as table format.",
    "Output Format": "Battlecard table",
    "Notes": "建議搭配內部 win/loss notes 一起餵給模型。",
    "Source URL": "https://academy.openai.com/public/clubs/work-users-ynjqu/resources/use-cases-sales"
  },
  {
    "ID": "SLS-COMP-002",
    "Category": "Competitive",
    "Stage": "Enablement",
    "Use Case": "Competitive positioning analysis",
    "When to Use": "要做 battlecard、提案對比、管理層 brief。",
    "Required Inputs": "competitor, our_strengths",
    "Variable List": "{{competitor}}=競品\n{{our_strengths}}=我方強項",
    "Prompt Quick ZH": "我正在準備 {{competitor}} 的競品分析。請研究其定價、定位、近期 win/loss、sales motion，並跟我們的 {{our_strengths}} 做比較，輸出 1 頁摘要並附引用。",
    "Prompt Robust ZH": "請對 {{competitor}} 進行 competitive positioning analysis。\n研究：定價模型、產品定位、近期客戶 win/loss、銷售模式。\n我方強項：{{our_strengths}}。\n輸出：1) 競品概覽 2) 價格/包裝假設 3) 近期動向與訊號 4) 與我方差異表 5) 建議話術與避雷。請附來源連結。",
    "Prompt Reference EN": "I’m preparing a competitive battlecard for [competitor name]. Research their pricing model, product positioning, recent customer wins/losses, and sales motion. Compare it to ours based on these strengths: [insert]. Output a 1-page summary with citations.",
    "Output Format": "1頁摘要 + 引用",
    "Notes": "需要即時資訊時，務必搭配網路搜尋。",
    "Source URL": "https://academy.openai.com/public/clubs/work-users-ynjqu/resources/use-cases-sales"
  },
  {
    "ID": "SLS-COMP-003",
    "Category": "Competitive",
    "Stage": "Enablement",
    "Use Case": "Sales enablement one-pager",
    "When to Use": "新人訓練、campaign 啟動、產品更新後。",
    "Required Inputs": "product, persona, key_benefits, use_cases, differentiators",
    "Variable List": "{{product}}=產品\n{{persona}}=角色\n{{key_benefits}}=效益\n{{use_cases}}=使用情境\n{{differentiators}}=差異化",
    "Prompt Quick ZH": "請做一份讓 reps 對 {{persona}} 銷售 {{product}} 的 one-pager。請包含關鍵效益、功能、使用情境與競品差異化。",
    "Prompt Robust ZH": "請撰寫一份可直接貼進文件的 sales enablement one-pager，協助 reps 對 {{persona}} 推薦 {{product}}。\n素材：效益={{key_benefits}}；情境={{use_cases}}；差異化={{differentiators}}。\n輸出：一句話價值主張、3 大痛點對應解法、5 個重點、2 個 mini cases、建議 CTA。",
    "Prompt Reference EN": "Create a one-pager to help reps pitch [product name] to [persona]. Include key benefits, features, common use cases, and competitor differentiators. Format as copy-ready enablement doc.",
    "Output Format": "Copy-ready one-pager",
    "Notes": "很適合作為新手業務的標準教材。",
    "Source URL": "https://academy.openai.com/public/clubs/work-users-ynjqu/resources/use-cases-sales"
  },
  {
    "ID": "SLS-COMP-004",
    "Category": "Competitive",
    "Stage": "Discovery",
    "Use Case": "Sales objection rebuttals",
    "When to Use": "遇到價格、導入成本、時程等常見異議。",
    "Required Inputs": "objections, proof_or_story",
    "Variable List": "{{objections}}=2-3 個異議\n{{proof_or_story}}=案例/數據/故事",
    "Prompt Quick ZH": "請針對以下異議，寫出自然、有自信的 rebuttals：{{objections}}。如有可用佐證：{{proof_or_story}}。",
    "Prompt Robust ZH": "請為以下 2-3 個 sales objections 產出 rebuttals：{{objections}}。可用佐證：{{proof_or_story}}。\n每條輸出固定為：1) 同理句 2) 回應主體 3) 反問/釐清 4) Next step。請避免太像背稿。",
    "Prompt Reference EN": "Create rebuttals to these common objections: [insert 2–3 objections]. Make them sound natural and confident, and include a backup stat or story where useful. Output as list.",
    "Output Format": "每條異議 4 段式回覆",
    "Notes": "實務上可再加一欄「禁用說法」。",
    "Source URL": "https://academy.openai.com/public/clubs/work-users-ynjqu/resources/use-cases-sales"
  },
  {
    "ID": "SLS-COMP-005",
    "Category": "Competitive",
    "Stage": "Enablement",
    "Use Case": "Public-domain customer proof points",
    "When to Use": "建立案例素材庫、對外簡報、競品比較。",
    "Required Inputs": "topic",
    "Variable List": "{{topic}}=我方產品或競品",
    "Prompt Quick ZH": "請研究公開網路上關於 {{topic}} 的評論、社群提及與見證，整理客戶在稱讚與抱怨什麼，並附連結。",
    "Prompt Robust ZH": "請在公開網路上研究 {{topic}} 的 reviews、social mentions 與 testimonials。\n輸出：1) 5 個重點引述（含 persona 與來源連結）2) 稱讚 Top3 3) 抱怨 Top3 4) 可用於銷售話術的 3 個 proof points。",
    "Prompt Reference EN": "Research recent online reviews, social mentions, and testimonials about [our product OR competitor product]. Focus on what customers are praising or criticizing. Summarize top 5 quotes, what persona each came from, and where it was posted. Include links.",
    "Output Format": "引述 + 來源連結 + 洞察",
    "Notes": "公開引用前，需確認法務與品牌使用規則。",
    "Source URL": "https://academy.openai.com/public/clubs/work-users-ynjqu/resources/use-cases-sales"
  },
  {
    "ID": "SLS-DATA-001",
    "Category": "Data",
    "Stage": "Pipeline",
    "Use Case": "Pipeline conversion rates by stage",
    "When to Use": "pipeline review、漏斗優化、管理層檢討。",
    "Required Inputs": "pipeline_csv, stages",
    "Variable List": "{{pipeline_csv}}=pipeline 匯出\n{{stages}}=stage 定義（可空）",
    "Prompt Quick ZH": "請分析這份 sales pipeline 匯出資料，計算各 stage 轉換率並找出最大掉點。資料：{{pipeline_csv}}。",
    "Prompt Robust ZH": "請分析 {{pipeline_csv}}，計算每個 stage 到下一 stage 的轉換率，並找出最大 drop-off。若 {{stages}} 未提供，請先列出你推定的 stage 定義。\n輸出：8 行摘要 + 轉換率表格 + 5 個改善建議。",
    "Prompt Reference EN": "Analyze this sales pipeline export. Calculate conversion rates between each stage and identify the biggest drop-off point. Data: [Upload pipeline CSV]. Output a short summary and a table of conversion % by stage.",
    "Output Format": "摘要 + 轉換率表格",
    "Notes": "若欄位不一致，先要求模型解釋其欄位對應邏輯。",
    "Source URL": "https://academy.openai.com/public/clubs/work-users-ynjqu/resources/use-cases-sales"
  },
  {
    "ID": "SLS-DATA-002",
    "Category": "Data",
    "Stage": "Performance",
    "Use Case": "Top-performing reps by close rate",
    "When to Use": "績效檢視、coach、團隊 benchmarking。",
    "Required Inputs": "rep_performance_csv",
    "Variable List": "{{rep_performance_csv}}=活動/成交資料",
    "Prompt Quick ZH": "根據 {{rep_performance_csv}} 計算每位 rep 的 close rate 並排名，並為每位 rep 寫一句強項描述。",
    "Prompt Robust ZH": "請從 {{rep_performance_csv}} 計算每位 rep 的 close rate 並排名。\n輸出：1) ranked list（rep、close rate、樣本數）2) 每位 rep 的強項一句話 3) Top 3 的可複製行為。",
    "Prompt Reference EN": "From this dataset of rep activities and closed deals, calculate the close rate for each rep and rank them. Data: [Upload rep performance CSV]. Output a ranked list and a sentence for each rep’s strength.",
    "Output Format": "排名 + 強項摘要",
    "Notes": "注意樣本數過小的 rep 可能要標註。",
    "Source URL": "https://academy.openai.com/public/clubs/work-users-ynjqu/resources/use-cases-sales"
  },
  {
    "ID": "SLS-DATA-003",
    "Category": "Data",
    "Stage": "Performance",
    "Use Case": "Deal velocity across quarters",
    "When to Use": "分析銷售週期變化、找出流程瓶頸。",
    "Required Inputs": "crm_export",
    "Variable List": "{{crm_export}}=CRM 匯出（含開啟/成交日期）",
    "Prompt Quick ZH": "請用 {{crm_export}} 計算每季平均 deal velocity（lead 到 close 天數），產出趨勢圖與摘要。",
    "Prompt Robust ZH": "請根據 {{crm_export}} 計算每季平均 deal velocity（從 lead 到 close 的天數），並用簡單圖表呈現趨勢。\n輸出：圖表 + 趨勢摘要 + 2-3 個降低 deal cycle 的建議。",
    "Prompt Reference EN": "Use this CRM export to calculate average deal velocity per quarter (days from lead to close). Data: [Upload with open/close dates]. Show velocity trend in a simple chart and summarize the trendline.",
    "Output Format": "圖表 + 摘要",
    "Notes": "若資料欄位不乾淨，先要求資料清理假設。",
    "Source URL": "https://academy.openai.com/public/clubs/work-users-ynjqu/resources/use-cases-sales"
  },
  {
    "ID": "SLS-DATA-004",
    "Category": "Data",
    "Stage": "Pipeline",
    "Use Case": "Campaign attribution to closed deals",
    "When to Use": "Marketing 與 Sales 對齊時。",
    "Required Inputs": "campaign_plus_deals_export",
    "Variable List": "{{campaign_plus_deals_export}}=campaign + deal 匯出",
    "Prompt Quick ZH": "請將 campaign 來源與 closed-won deals 配對，找出帶來最多 closed revenue 的 campaign。資料：{{campaign_plus_deals_export}}。",
    "Prompt Robust ZH": "請分析 {{campaign_plus_deals_export}}，找出各 campaign 對 closed-won revenue 的貢獻。\n輸出：1) 排名清單（campaign、closed revenue、件數、平均 deal size）2) Top 3 活動為何有效 3) 下一季優化建議。",
    "Prompt Reference EN": "Match campaign sources to closed-won deals from this data. Identify which campaign drove the most closed revenue. Data: [Upload campaign + deal export]. Output a ranked list and a short campaign summary.",
    "Output Format": "排名 + 短摘要",
    "Notes": "適合與 marketing attribution model 搭配。",
    "Source URL": "https://academy.openai.com/public/clubs/work-users-ynjqu/resources/use-cases-sales"
  },
  {
    "ID": "SLS-DATA-005",
    "Category": "Data",
    "Stage": "Performance",
    "Use Case": "Performance comparison chart",
    "When to Use": "績效 coaching、季度回顧。",
    "Required Inputs": "rep_table",
    "Variable List": "{{rep_table}}=rep 季度表現表",
    "Prompt Quick ZH": "這是 rep 每季表現表：{{rep_table}}。請比較 top vs bottom performers，做出趨勢圖並指出關鍵差異。",
    "Prompt Robust ZH": "請根據 {{rep_table}} 比較 top performers 與 bottom performers。\n輸出：1) 趨勢圖 2) 3-5 點關鍵差異洞察 3) 對 bottom performers 的 3 個可執行改善建議。",
    "Prompt Reference EN": "Here’s a table of rep performance by quarter: [paste data]. Compare top vs bottom performers. Show chart with trends and call out key differences. Output as table + insights.",
    "Output Format": "圖表 + 洞察 + 建議",
    "Notes": "適合搭配績效 coaching。",
    "Source URL": "https://academy.openai.com/public/clubs/work-users-ynjqu/resources/use-cases-sales"
  },
  {
    "ID": "SLS-VIS-001",
    "Category": "Visuals",
    "Stage": "Enablement",
    "Use Case": "Sales process in funnel view",
    "When to Use": "onboarding 文件、sales kickoff、教育訓練。",
    "Required Inputs": "stages, style",
    "Variable List": "{{stages}}=sales stages\n{{style}}=風格",
    "Prompt Quick ZH": "請做一張 funnel graphic 呈現我們的 sales stages：{{stages}}。風格：{{style}}，適合 onboarding 文件。",
    "Prompt Robust ZH": "請生成一張可貼到文件或簡報中的 funnel graphic，呈現 {{stages}}。\n風格：{{style}}。要求：清楚可讀、視覺簡潔、適合銷售培訓。",
    "Prompt Reference EN": "Create a funnel graphic showing our sales stages: [insert stages]. Make it clean and easy to read for onboarding docs. Output as simple image.",
    "Output Format": "圖片",
    "Notes": "若無法生圖，可改成輸出設計規格或 SVG 說明。",
    "Source URL": "https://academy.openai.com/public/clubs/work-users-ynjqu/resources/use-cases-sales"
  },
  {
    "ID": "SLS-VIS-002",
    "Category": "Visuals",
    "Stage": "Enablement",
    "Use Case": "Standard B2B sales funnel image",
    "When to Use": "簡報、內訓、提案素材。",
    "Required Inputs": "none",
    "Variable List": "固定 stages：Prospecting / Discovery / Demo / Proposal / Closed Won/Lost",
    "Prompt Quick ZH": "請生成一張標準 B2B SaaS 銷售漏斗圖，階段為 Prospecting、Discovery、Demo、Proposal、Closed Won/Lost。",
    "Prompt Robust ZH": "請生成一張標準 B2B SaaS sales funnel 圖，包含 Prospecting、Discovery、Demo、Proposal、Closed Won/Lost。\n要求：乾淨、現代、圖示清楚、文字可讀，適合放入簡報或 enablement 文件。",
    "Prompt Reference EN": "Create an image of a standard B2B SaaS sales funnel with these stages: Prospecting, Discovery, Demo, Proposal, Closed Won/Lost. Use clean, modern icons and text labels. Output should be clear enough for use in a slide or enablement doc.",
    "Output Format": "圖片",
    "Notes": "適合做成標準教材頁。",
    "Source URL": "https://academy.openai.com/public/clubs/work-users-ynjqu/resources/use-cases-sales"
  },
  {
    "ID": "SLS-VIS-003",
    "Category": "Visuals",
    "Stage": "Enablement",
    "Use Case": "Illustrate key sales personas",
    "When to Use": "一頁紙、訓練教材、角色說明。",
    "Required Inputs": "none",
    "Variable List": "固定 persona：CFO / VP IT / Operations Manager",
    "Prompt Quick ZH": "請為 3 個 persona 生成專業插圖：中型企業 CFO、全球企業 VP of IT、物流公司的 Operations Manager。",
    "Prompt Robust ZH": "請生成 3 個銷售 persona 的專業插圖：1) mid-market CFO 2) global enterprise VP of IT 3) logistics firm 的 Operations Manager。\n風格：扁平、現代、適合放到 one-pager 或 training slide。",
    "Prompt Reference EN": "Create professional illustrations for 3 personas: (1) CFO of a mid-market company, (2) VP of IT at a global enterprise, and (3) Operations Manager at a logistics firm. Style should be flat and modern, ideal for use in a one-pager or training slide.",
    "Output Format": "3 張圖片",
    "Notes": "若客戶有品牌規範，可額外加上色系與人物設定。",
    "Source URL": "https://academy.openai.com/public/clubs/work-users-ynjqu/resources/use-cases-sales"
  },
  {
    "ID": "SLS-VIS-004",
    "Category": "Visuals",
    "Stage": "Planning",
    "Use Case": "Territory coverage map",
    "When to Use": "territory 說明、SKO、管理報告。",
    "Required Inputs": "none",
    "Variable List": "固定區域：West / Central / East",
    "Prompt Quick ZH": "請製作一張簡化的美國 territory coverage map，區域分為 West、Central、East。",
    "Prompt Robust ZH": "請生成一張簡化版美國 territory map，依區域分成 West、Central、East。\n要求：區域顏色清楚、主要州別標示、風格乾淨，適合放在 sales kickoff deck。",
    "Prompt Reference EN": "Create a simplified U.S. map showing sales territories split by region: West, Central, East. Use distinctive color zones and label key states. Output should look clean and suitable for a sales kickoff deck.",
    "Output Format": "圖片",
    "Notes": "若不是美國市場，可自行改成其他地區。",
    "Source URL": "https://academy.openai.com/public/clubs/work-users-ynjqu/resources/use-cases-sales"
  },
  {
    "ID": "SLS-VIS-005",
    "Category": "Visuals",
    "Stage": "Internal",
    "Use Case": "Team celebration graphic",
    "When to Use": "內部 newsletter、團隊表揚、月會。",
    "Required Inputs": "name_or_placeholder, brand_vibe",
    "Variable List": "{{name_or_placeholder}}=姓名或占位\n{{brand_vibe}}=品牌氛圍",
    "Prompt Quick ZH": "請設計一張「Top Rep of the Month」慶祝圖，包含 {{name_or_placeholder}} 與獎盃/徽章元素，風格符合 {{brand_vibe}}。",
    "Prompt Robust ZH": "請設計一張現代、有趣的慶祝圖，主題為「Top Rep of the Month」。\n需包含：{{name_or_placeholder}} 的占位、照片占位、獎盃或徽章元素。\n風格：符合 {{brand_vibe}}，適合內部品牌或 newsletter。",
    "Prompt Reference EN": "Design a fun, modern graphic to celebrate “Top Rep of the Month.” Include a placeholder for name/photo and stylized trophy or badge. Style should match internal brand or newsletter vibe.",
    "Output Format": "圖片",
    "Notes": "非常適合提高 adoption，因為容易出成果。",
    "Source URL": "https://academy.openai.com/public/clubs/work-users-ynjqu/resources/use-cases-sales"
  }
];